spring:
  application:
    name: kc-example
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

authentication:
  shared:
    issuer-uri:
      - http://localhost:8080/realms/xxx
      - http://localhost:8080/realms/yyy
logging:
  level:
    root: debug

