spring:
  application:
    name: kc-example
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

authentication:
  shared:
    issuer-uri:
      - http://localhost:8080/realms/customer-auth
      - http://localhost:8080/realms/merchant-auth
logging:
  level:
    root: info

server:
  port: 8081
